databases:
  - name: deadlineguard-db
    plan: free

services:
  - type: web
    name: deadlineguard-api
    env: docker
    plan: free
    dockerContext: ./deadlineguard-api
    dockerfilePath: ./deadlineguard-api/Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: deadlineguard-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: deadlineguard-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: deadlineguard-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: deadlineguard-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: deadlineguard-db
          property: password
      - key: FRONTEND_URL
        value: https://deadlineguard-ui.onrender.com
      - key: PORT
        value: 8080

  - type: web
    name: deadlineguard-ui
    env: static
    buildCommand: cd deadlineguard-ui && npm install && npm run build
    staticPublishPath: ./deadlineguard-ui/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://deadlineguard-api.onrender.com/api
